/**
 * mockData.js
 * High-fidelity demonstration data strictly mirroring the Django Backend models:
 * - Repository (name, full_name, github_url, owner)
 * - PullRequest (github_pr_id, number, title, author, source_branch, target_branch, status)
 * - Review (status, summary, health_score, health_grade, risk_level, health_details)
 * - Finding (finding_type, severity, file_path, line_number, title, description, suggestion)
 *
 * Plus Tree-sitter AST & Google Gemini metadata matching ast_checker.py and llm_reviewer.py.
 */

export const MOCK_REPOSITORIES = [
  {
    id: 1,
    name: 'neetcode-submissions',
    full_name: 'nilakshib-star/neetcode-submissions',
    owner: 'nilakshib-star',
    owner_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    github_url: 'https://github.com/nilakshib-star/neetcode-submissions',
    risk_profile: 'Standard sensitivity',
    scanning_enabled: true,
    webhook_installed: true,
    last_scan: '12 minutes ago',
    total_prs: 14,
    total_reviews: 18,
    issues_count: 5,
    critical_issues: 0,
    language: 'Python',
    visibility: 'public',
  },
  {
    id: 2,
    name: 'github-ai-code-reviewer',
    full_name: 'nilakshib-star/github-ai-code-reviewer',
    owner: 'nilakshib-star',
    owner_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    github_url: 'https://github.com/nilakshib-star/github-ai-code-reviewer',
    risk_profile: 'High sensitivity',
    scanning_enabled: true,
    webhook_installed: true,
    last_scan: '35 minutes ago',
    total_prs: 29,
    total_reviews: 42,
    issues_count: 8,
    critical_issues: 2,
    language: 'Python / React',
    visibility: 'public',
  },
  {
    id: 3,
    name: 'auth-service-core',
    full_name: 'nilakshib-star/auth-service-core',
    owner: 'nilakshib-star',
    owner_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    github_url: 'https://github.com/nilakshib-star/auth-service-core',
    risk_profile: 'Critical infrastructure',
    scanning_enabled: true,
    webhook_installed: true,
    last_scan: '3 hours ago',
    total_prs: 8,
    total_reviews: 11,
    issues_count: 3,
    critical_issues: 1,
    language: 'Python',
    visibility: 'private',
  },
  {
    id: 4,
    name: 'payment-gateway-v2',
    full_name: 'nilakshib-star/payment-gateway-v2',
    owner: 'nilakshib-star',
    owner_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    github_url: 'https://github.com/nilakshib-star/payment-gateway-v2',
    risk_profile: 'Financial data PCI',
    scanning_enabled: false,
    webhook_installed: false,
    last_scan: '2 days ago',
    total_prs: 6,
    total_reviews: 6,
    issues_count: 2,
    critical_issues: 0,
    language: 'TypeScript',
    visibility: 'private',
  },
  {
    id: 5,
    name: 'infra-cloud-terraform',
    full_name: 'nilakshib-star/infra-cloud-terraform',
    owner: 'nilakshib-star',
    owner_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    github_url: 'https://github.com/nilakshib-star/infra-cloud-terraform',
    risk_profile: 'Standard sensitivity',
    scanning_enabled: true,
    webhook_installed: true,
    last_scan: '1 day ago',
    total_prs: 12,
    total_reviews: 15,
    issues_count: 1,
    critical_issues: 0,
    language: 'HCL / Docker',
    visibility: 'public',
  },
];

export const MOCK_PULL_REQUESTS = [
  {
    id: 101,
    repo_id: 2,
    repo_name: 'github-ai-code-reviewer',
    repo_full_name: 'nilakshib-star/github-ai-code-reviewer',
    github_pr_id: 9942,
    number: 42,
    title: 'Fix authentication token validation & prevent session replay attacks',
    author: 'nilakshib-star',
    author_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    source_branch: 'fix/jwt-expiry-validation',
    target_branch: 'main',
    status: 'open',
    review_verdict: 'request_changes',
    review_status: 'Completed',
    health_score: 72,
    health_grade: 'B',
    risk_level: 'Medium',
    issues_count: 4,
    critical_count: 1,
    high_count: 1,
    medium_count: 1,
    low_count: 1,
    created_at: '2026-10-07T08:30:00Z',
    updated_at: '2026-10-07T09:15:00Z',
    additions: 148,
    deletions: 34,
    changed_files_count: 4,
  },
  {
    id: 102,
    repo_id: 1,
    repo_name: 'neetcode-submissions',
    repo_full_name: 'nilakshib-star/neetcode-submissions',
    github_pr_id: 9941,
    number: 19,
    title: 'feat: add LRU Cache and Graph traversal solutions in Python',
    author: 'developer-alex',
    author_avatar: 'https://avatars.githubusercontent.com/u/67890?v=4',
    source_branch: 'feat/lru-cache-solution',
    target_branch: 'main',
    status: 'open',
    review_verdict: 'approve',
    review_status: 'Completed',
    health_score: 96,
    health_grade: 'A+',
    risk_level: 'Low',
    issues_count: 1,
    critical_count: 0,
    high_count: 0,
    medium_count: 0,
    low_count: 1,
    created_at: '2026-10-06T14:20:00Z',
    updated_at: '2026-10-06T14:45:00Z',
    additions: 82,
    deletions: 4,
    changed_files_count: 2,
  },
  {
    id: 103,
    repo_id: 3,
    repo_name: 'auth-service-core',
    repo_full_name: 'nilakshib-star/auth-service-core',
    github_pr_id: 9940,
    number: 28,
    title: 'refactor: decouple OAuth refresh token rotation pipeline',
    author: 'sec-eng-marcus',
    author_avatar: 'https://avatars.githubusercontent.com/u/54321?v=4',
    source_branch: 'refactor/oauth-rotation',
    target_branch: 'main',
    status: 'open',
    review_verdict: 'comment',
    review_status: 'Completed',
    health_score: 84,
    health_grade: 'B+',
    risk_level: 'Low',
    issues_count: 3,
    critical_count: 0,
    high_count: 1,
    medium_count: 2,
    low_count: 0,
    created_at: '2026-10-05T19:10:00Z',
    updated_at: '2026-10-05T20:05:00Z',
    additions: 210,
    deletions: 95,
    changed_files_count: 6,
  },
  {
    id: 104,
    repo_id: 2,
    repo_name: 'github-ai-code-reviewer',
    repo_full_name: 'nilakshib-star/github-ai-code-reviewer',
    github_pr_id: 9939,
    number: 40,
    title: 'feat: add Tree-sitter AST syntax validator for Python & JS',
    author: 'nilakshib-star',
    author_avatar: 'https://avatars.githubusercontent.com/u/9919?v=4',
    source_branch: 'feat/tree-sitter-integration',
    target_branch: 'main',
    status: 'merged',
    review_verdict: 'approve',
    review_status: 'Completed',
    health_score: 92,
    health_grade: 'A',
    risk_level: 'Low',
    issues_count: 2,
    critical_count: 0,
    high_count: 0,
    medium_count: 1,
    low_count: 1,
    created_at: '2026-10-04T11:00:00Z',
    updated_at: '2026-10-04T12:30:00Z',
    additions: 340,
    deletions: 18,
    changed_files_count: 5,
  },
  {
    id: 105,
    repo_id: 5,
    repo_name: 'infra-cloud-terraform',
    repo_full_name: 'nilakshib-star/infra-cloud-terraform',
    github_pr_id: 9938,
    number: 12,
    title: 'chore: configure Redis cluster caching for Celery broker',
    author: 'devops-lead',
    author_avatar: 'https://avatars.githubusercontent.com/u/44332?v=4',
    source_branch: 'infra/redis-broker-cluster',
    target_branch: 'main',
    status: 'open',
    review_verdict: 'analyzing',
    review_status: 'Analyzing',
    health_score: null,
    health_grade: 'Pending',
    risk_level: 'Evaluating',
    issues_count: 0,
    critical_count: 0,
    high_count: 0,
    medium_count: 0,
    low_count: 0,
    created_at: '2026-10-07T13:40:00Z',
    updated_at: '2026-10-07T13:42:00Z',
    additions: 45,
    deletions: 12,
    changed_files_count: 3,
  },
];

export const MOCK_REVIEWS_BY_PR = {
  42: {
    id: 501,
    pr_id: 101,
    pr_number: 42,
    repo_full_name: 'nilakshib-star/github-ai-code-reviewer',
    verdict: 'request_changes',
    status: 'Completed',
    summary:
      'The PR introduces essential JWT expiration validation but includes an unhandled signature bypass when verifying tokens without algorithm constraints. AST analysis also identified a high cyclomatic complexity block and missing docstrings in the auth decorator.',
    health_score: 72,
    health_grade: 'B',
    risk_level: 'Medium',
    execution_time_seconds: 4.8,
    llm_model_used: 'Google Gemini 2.5 Flash',
    ast_parser_used: 'Tree-sitter Python v0.25',
    pipeline_stages: [
      { step: 'PR Created', time: '08:30:01', status: 'completed' },
      { step: 'Webhook Received', time: '08:30:03', status: 'completed' },
      { step: 'Queued (Celery)', time: '08:30:04', status: 'completed' },
      { step: 'Tree-sitter AST', time: '08:30:05', status: 'completed' },
      { step: 'Gemini LLM Review', time: '08:30:07', status: 'completed' },
      { step: 'Review Posted to GitHub', time: '08:30:08', status: 'completed' },
    ],
    health_report: {
      score: 72,
      grade: 'B',
      risk_level: 'Medium',
      badges: ['⚡ Fast Diff', '⚠️ Missing Tests', '🔒 Auth Boundary'],
      recommendations: [
        'Add automated unit test verifying expired token rejection.',
        'Explicitly restrict algorithms parameter to ["HS256", "RS256"] in jwt.decode.',
        'Refactor token_refresh_flow() to reduce cyclomatic nesting depth (> 4 levels).',
      ],
      metrics: {
        additions: 148,
        deletions: 34,
        files_changed: 4,
        test_ratio: 0.18,
        ast_findings_count: 2,
        llm_findings_count: 3,
      },
    },
    findings: [
      {
        id: 'f-1',
        title: 'Critical JWT algorithm confusion vulnerability',
        finding_type: 'Security',
        severity: 'Critical',
        file_path: 'backend/PRreview/review/github_auth.py',
        line_number: 42,
        analysis_source: 'BOTH', // Tree-sitter detected missing arg; Gemini flagged security impact
        description:
          'jwt.decode() is invoked without verifying the header algorithm. Attackers can forge HMAC-signed tokens with public keys (CVE-2015-9235 pattern).',
        why_problem:
          'When verifying JSON Web Tokens without specifying allowed algorithms, arbitrary signatures or the "none" algorithm can be accepted, bypassing all authentication safeguards.',
        suggestion:
          'Explicitly specify allowed algorithms: algorithms=["HS256"] or your chosen cryptographic scheme.',
        code_diff: {
          original: 'decoded = jwt.decode(token, secret_key)\nreturn decoded["user_id"]',
          suggested: 'decoded = jwt.decode(\n    token,\n    secret_key,\n    algorithms=["HS256"],\n    options={"require": ["exp", "iat"]}\n)\nreturn decoded["user_id"]',
        },
      },
      {
        id: 'f-2',
        title: 'Excessive cyclomatic complexity in validation loop',
        finding_type: 'Performance',
        severity: 'High',
        file_path: 'backend/PRreview/review/github_service.py',
        line_number: 88,
        analysis_source: 'AST', // Tree-sitter
        description:
          'Tree-sitter AST analyzer detected function `validate_repo_access` has 6 nested if/for conditions spanning 54 lines.',
        why_problem:
          'Deep nested conditional statements increase cognitive complexity, make edge cases prone to regression, and hinder maintainability.',
        suggestion:
          'Use guard clauses to return early and extract installation lookup into a helper function.',
        code_diff: {
          original: 'def validate_repo_access(user, repo):\n    if user.is_authenticated:\n        if repo in user.repos:\n            for permission in repo.permissions:\n                if permission.level == "admin":\n                    return True\n    return False',
          suggested: 'def validate_repo_access(user, repo):\n    if not user.is_authenticated:\n        return False\n    return repo.user_has_admin(user)',
        },
      },
      {
        id: 'f-3',
        title: 'Hardcoded fallback secret string detected',
        finding_type: 'Security',
        severity: 'Medium',
        file_path: 'backend/PRreview/PRreview/settings.py',
        line_number: 28,
        analysis_source: 'AST',
        description:
          'Tree-sitter AST regex rule HARDCODED_SECRET matched default string value in `SECRET_KEY = os.getenv("SECRET_KEY", "default-insecure-key")`.',
        why_problem:
          'Fallback insecure keys risk being loaded accidentally in staging or production deployments.',
        suggestion:
          'Raise ImproperlyConfigured exception when SECRET_KEY is not defined in environment variables.',
        code_diff: {
          original: 'SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-key")',
          suggested: 'SECRET_KEY = os.environ["SECRET_KEY"]  # Raise KeyError immediately if missing',
        },
      },
      {
        id: 'f-4',
        title: 'Missing docstring on public webhook endpoint handler',
        finding_type: 'Code Quality',
        severity: 'Low',
        file_path: 'backend/PRreview/review/views.py',
        line_number: 14,
        analysis_source: 'AI',
        description:
          'Public DRF view `github_webhook` lacks documentation explaining expected headers (`X-GitHub-Event`, `X-Hub-Signature-256`) and return payload format.',
        why_problem:
          'Future team members and API consumers need clear documentation on external webhook contracts.',
        suggestion:
          'Add a descriptive Google/Sphinx style docstring to the endpoint definition.',
        code_diff: {
          original: '@csrf_exempt\ndef github_webhook(request):\n    ...',
          suggested: '@csrf_exempt\ndef github_webhook(request):\n    """\n    Handle incoming GitHub App webhooks.\n    Validates HMAC SHA256 signature and enqueues Celery review job.\n    """\n    ...',
        },
      },
    ],
  },
  19: {
    id: 502,
    pr_id: 102,
    pr_number: 19,
    repo_full_name: 'nilakshib-star/neetcode-submissions',
    verdict: 'approve',
    status: 'Completed',
    summary:
      'Excellent clean implementation of Doubly Linked List with Hash Map for O(1) LRU Cache get and put operations. Code is well formatted, types are declared, and tests pass with 100% assertion coverage.',
    health_score: 96,
    health_grade: 'A+',
    risk_level: 'Low',
    execution_time_seconds: 3.2,
    llm_model_used: 'Google Gemini 2.5 Flash',
    ast_parser_used: 'Tree-sitter Python v0.25',
    pipeline_stages: [
      { step: 'PR Created', time: '14:20:00', status: 'completed' },
      { step: 'Webhook Received', time: '14:20:02', status: 'completed' },
      { step: 'Queued (Celery)', time: '14:20:03', status: 'completed' },
      { step: 'Tree-sitter AST', time: '14:20:04', status: 'completed' },
      { step: 'Gemini LLM Review', time: '14:20:06', status: 'completed' },
      { step: 'Review Posted to GitHub', time: '14:20:07', status: 'completed' },
    ],
    health_report: {
      score: 96,
      grade: 'A+',
      risk_level: 'Low',
      badges: ['⭐ Exemplary Code', '🧪 Full Test Coverage', '⚡ O(1) Verified'],
      recommendations: [
        'Consider adding typing annotations for Node prev and next pointers for stricter mypy checks.',
      ],
      metrics: {
        additions: 82,
        deletions: 4,
        files_changed: 2,
        test_ratio: 0.65,
        ast_findings_count: 0,
        llm_findings_count: 1,
      },
    },
    findings: [
      {
        id: 'f-10',
        title: 'Optional type hinting enhancement for linked list node pointers',
        finding_type: 'Best Practice',
        severity: 'Low',
        file_path: 'solutions/lru_cache.py',
        line_number: 12,
        analysis_source: 'AI',
        description:
          'Using `Optional["Node"]` for `prev` and `next` attributes makes static type checkers like mypy verify None safety.',
        why_problem:
          'Untyped self-referencing pointers may occasionally cause attribute errors if sentinel head/tail nodes are improperly initialized.',
        suggestion:
          'Add `from __future__ import annotations` and type the node pointers as `Node | None`.',
        code_diff: {
          original: 'self.prev = None\nself.next = None',
          suggested: 'self.prev: Node | None = None\nself.next: Node | None = None',
        },
      },
    ],
  },
};

export const MOCK_ANALYTICS = {
  kpis: {
    prs_merged: 68,
    median_cycle_time: '2.1h',
    time_to_first_review: '38s',
    ai_acceptance_rate: '86.4%',
    median_pr_size: '124 lines',
    automated_coverage: '99.1%',
  },
  review_decisions: [
    { name: 'Approved', value: 68, color: '#10b981' },
    { name: 'Commented', value: 24, color: '#0284c7' },
    { name: 'Changes Requested', value: 16, color: '#f59e0b' },
  ],
  cycle_time_by_stage: [
    { stage: 'Mon', 'Pre-Review': 0.4, Pickup: 0.2, Review: 0.1, Merge: 1.2 },
    { stage: 'Tue', 'Pre-Review': 0.6, Pickup: 0.3, Review: 0.1, Merge: 1.8 },
    { stage: 'Wed', 'Pre-Review': 0.3, Pickup: 0.2, Review: 0.1, Merge: 1.1 },
    { stage: 'Thu', 'Pre-Review': 0.8, Pickup: 0.4, Review: 0.1, Merge: 2.1 },
    { stage: 'Fri', 'Pre-Review': 0.5, Pickup: 0.3, Review: 0.1, Merge: 1.6 },
    { stage: 'Sat', 'Pre-Review': 0.2, Pickup: 0.1, Review: 0.1, Merge: 0.9 },
    { stage: 'Sun', 'Pre-Review': 0.3, Pickup: 0.1, Review: 0.1, Merge: 0.8 },
  ],
  issues_by_category: [
    { category: 'Security', count: 18, color: '#ef4444' },
    { category: 'AST Syntax/Scope', count: 14, color: '#8b5cf6' },
    { category: 'Performance', count: 26, color: '#f59e0b' },
    { category: 'Code Quality', count: 42, color: '#0284c7' },
    { category: 'Maintainability', count: 31, color: '#10b981' },
    { category: 'Best Practice', count: 22, color: '#6366f1' },
  ],
  source_detection_breakdown: [
    { month: 'May', ast: 32, llm: 54, hybrid: 18 },
    { month: 'Jun', ast: 45, llm: 68, hybrid: 28 },
    { month: 'Jul', ast: 58, llm: 82, hybrid: 39 },
    { month: 'Aug', ast: 72, llm: 95, hybrid: 48 },
    { month: 'Sep', ast: 89, llm: 112, hybrid: 62 },
    { month: 'Oct', ast: 104, llm: 128, hybrid: 74 },
  ],
};
